#Esse é um exercício em que vamos saber todas as informações sobre o tipo primitivo que for lido.
v= input('Digite algo:\n')
print('É numérico?')
print(v.isnumeric())
print('É letra?')
print(v.isalpha())
print('É alfanumérico?')
print(v.isalnum())
print('Está em maiúsculo?')
print(v.isupper())
print('Está em minúsculo?')
print(v.islower())
print('É um espaço?')
print(v.isspace())
print('Pode ser impresso?')
print(v.isprintable())
print('É decimal?')
print(v.isdecimal())
print('Está capitalizada?\n', v.istitle())
print('O tipo primitivo é:\n', type(v))
